// Piac location scenes and logic

const piacScenes = [
    {type:'narrative', text:'Megérkeztél a piacra. A tér nyüzsög az élettel, árusok kiabálják portékáikat.'},
    {type:'narrative', text:'A piac tele van különféle árukkal: friss zöldségekkel, fűszerekkel és kézműves termékekkel.'},
    {type:'narrative', text:'A gyilkosság helyszínéről származó gyümölcsök itt vehette az áldozat, érdemes lehet körülnézni az árusok között.'},
    {type:'narrative', text:'Feltünés mentesen kellene nyomoznod mivel a gyilkosságnak még nem ment híre.'},
    {type:'narrative', text:'Ebben az időszakban elég kevés helyen lehet gyümölcsöt kapni. Kiszúrsz egy árust, aki friss gyümölcsöket kínál eladásra, mind olyan mint a gyilkosság helyszínén találtak. A standja úgy néz ki mintha éppen kirabolták volna.'},
    {type:'narrative', text:'Odamész az árushoz.'},
    {type:'choices', prompt:'Mit teszel?', choices:[
        {id:'ask_fruits', label:'Megszólítod az árust', nextScene: 7, condition: 'notAbandonedGame'},
        {id:'ask_customers', label:'Körülnézel a piacon', nextScene: 27},
    ]},
    {type:'narrative', text:'Odamész az árushoz, aki éppen nagy erővel pakolja a pultját de felnéz rád és mosolyogva fogad.'},
    {type:'narrative', text:'Jó napot! Mit parancsol? Friss gyümölcsöket kínálok, ennél jobbat nem talál.', image:'pictures/characters/piaci_arus.png'},
    {type:'choices', prompt:'Mit kérdezel?', image:'pictures/characters/piaci_arus.png', evidencePrompt: 'Nyomok kérdezése', choices:[
        {id:'ask_sold', label:'Kérdezel hogy vásárolt ma itt egy cseléd', nextScene: 10},
        {id:'ask_quality', label:'Kérdezel mi történt a putjánál', nextScene: 13},
        {id:'help_packing', label:'Felajánlod a segítségedet a pakolásban (játék)', nextScene: 17, condition: 'piacIncidentHeard'},
        {id:'end_talk', label:'Befejezed a beszélgetést', nextScene: 6}
    ]},
    {type:'narrative', text:'A cselédről érdeklődsz, az áldozattról kihagyva azt a részt hogy meggyilkolták.'},
    {type:'narrative', text:'Na de kérem! Tudja maga hányan vásárolnak nálam? Ennél több információra lenne szükségem.', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Elég mérges lett az árus, inkább tovább pakolja a standot.', nextScene: 9},
    {type:'narrative', text:'Rákérdezel, hogy mi történt a pultjánál. Úgy néz ki mintha valaki szándékosan felborított volna néhány ládát amikben az áruk voltak.'},
    {type:'narrative', text:'Az árus arca elsötétedik és dühösen mesél.'},
    {type:'narrative', text:'Azok az átkozott ördögök! Talán 3-an vagy 4-en lehettek, néhány gyerek egyszercsak a semmiből megjelent folborították a ládákat és ellopták a földre esett gyümölcsöket. Ezek is a Ghostskin-t gyermekei lehettek. Elveszett gyerekek akiket rossz ember vezet.', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Mielőtt bármit tehettem volna máris eltűntek.', image:'pictures/characters/piaci_arus.png', nextScene: 9, setState: {piacIncidentHeard: true}},
    {type:'narrative', text:'Felajánlod a segítségedet az árusnak, hogy segíts visszapakolni a gyümölcsöket.'},
    {type:'narrative', text:'Az árus arca felderül és hálás mosollyal néz rád.'},
    {type:'narrative', text:'Ó, nagyon kedves öntől! Ez óriási segítség lenne!', image:'pictures/characters/piaci_arus.png', action: 'redirect', redirectUrl: 'game1.html'},
    {type:'narrative', text:'Maga tréfál velem? Ne rabolja tovább az időmet!', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Sikerült annyira felmérgelned az árust, hogy többé nem hajlandó rád figyelni.', nextScene: 6, setState: {piacMerchantAngry: true}},
    {type:'narrative', text:'Sikeresen segítettél az árusnak visszapakolni az összes gyümölcsöt.'},
    {type:'narrative', text:'Az árus hálás mosollyal néz rád.'},
    {type:'narrative', text:'Köszönöm szépen a segítségét! Nagyon hálás vagyok, ritka manapság az ilyen önzetlen segítség.', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Azok alapján mit a cseléd vásárolt és hogyan nézett ki ő csakis Charlotte cseléd lehetett. Vele volt a báró gyermeke is Sebastian.', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Annál többet nem tudok mondani mint, hogy vásároltak tőlem és elmentek. Nem figyeltem, hogy merre vagy mi történthetett velük a továbbiakban. Nincs több információm.', nextScene: 9, setState: {piacGameWon: true}},
    {type:'narrative', text:'Körülnézel a piacon, hogy láss-e bármilyen gyanús tevékenységet vagy tanút, aki segíthetne az ügyben.'},
    {type:'narrative', text:'A piac zsúfolt, emberek sürgölődnek minden irányban. Árusok kiabálnak, vásárlók alkudoznak.'},
    {type:'narrative', text:'Figyelmesen végigpásztázod a tömeget, keresve bármilyen szokatlan mozdulatot vagy viselkedést.'},
    {type:'narrative', text:'Távolabb az egyik árus standjánál kiszúrsz 3 gyereket. Rongyos ruhában vannak, és izgatottan suttognak egymás között.'},
    {type:'narrative', text:'Nem éppen úgy néznek ki mint akik vásárolni jöttek volna. Inkább úgy tűnik mintha valamit terveznének.'},
    {type:'narrative', text:'Elindulsz feléjük, hogy közelebbről megfigyeld őket.'},
    {type:'narrative', text:'De az egyik gyermek kiszúr téged a tömegben. Megbökik a másik kettőt és gyorsan eltűnnek a tömegben mielőtt elérhetnéd őket.'},
    {type:'narrative', text:'Ugye milyen idegesítő, hogyha beszélni akarsz velük akkor csak úgy elrohannak?', image:'pictures/characters/nevtelen.png'},
    {type:'narrative', text:'Oldalról szólít meg egy fiatal férfi. Nem tűnik barátságos jellemnek. Gyanúsan mosolyog rád, mint aki élvezte a látványt hogy elfutottak a gyerekek előlled.'/*, nextScene: 6*/},
    {type:'narrative', text:'Ilyen nagy tömeg nekik csak az előnyükre vál ha el akarnak futni. De tudd meg mindig van egy hely ahova haza kell menniük.', image:'pictures/characters/nevtelen.png'},
    {type:'narrative', text:'Ha legközelebb találkozunk, még talán segíthetek is kikérdezni őket.', image:'pictures/characters/nevtelen.png'},
    {type:'narrative', text:'A férfi elvegyül a tömegben mielőtt válaszolhatnál neki. Olyan mintha a fiúkat követné.', nextScene: 6},
    {type:'evidence_choices', prompt:'Melyik nyomról kérdezel?', image:'pictures/characters/piaci_arus.png', requiredItem: 'Gyümölcsök', choices:[
        {id:'gyumolcsok', label:'Gyümölcsök', nextScene: 40, requiresItem: 'Gyümölcsök'},
        {id:'kalapacs', label:'Kalapács', nextScene: 44, requiresItem: 'Kalapács'},
        {id:'kendo', label:'Kendő', nextScene: 48, requiresItem: 'Kendő'},
        {id:'back', label:'Vissza', nextScene: 9}
    ]},
    {type:'narrative', text:'Megmutatod az árusnak a gyümölcsöket amelyeket a helyszínen találtatok.'},
    {type:'narrative', text:'Az árus közelebbről megnézi őket.'},
    {type:'narrative', text:'Lehet nálam vették, talán ma amilyen frissek. Nem sokan árulnak ilyen jó állapotú gyümölcsöt manapság.', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Az árus továbbra is a gyümölcsöket nézegeti aztán újra felnéz rád.', nextScene: 9, image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Megmutatod az árusnak a kalapácsot.'},
    {type:'narrative', text:'Az árus arcára rémület ül és hátralép.'},
    {type:'narrative', text:'Mi ez?! Ez vér rajta! Miért mutat nekem ilyet?!', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Az árus láthatóan felkavarodott, inkább gyorsan elrakod a kalapácsot.', nextScene: 9},
    {type:'narrative', text:'Megmutatod az árusnak a kendőt a báró címerével.'},
    {type:'narrative', text:'Az árus figyelmesen megnézi a kendőt.'},
    {type:'narrative', text:'Ő... ez egy kendő. Nem szabó vagyok.', image:'pictures/characters/piaci_arus.png'},
    {type:'narrative', text:'Az árus visszaadja neked a kendőt és továbbra is válaszol a kérdéseidre.', nextScene: 9, image:'pictures/characters/piaci_arus.png'}

];

const piacBackground = 'pictures/piac.png';
